---
  - name: Install remote_syslog from papertrail
    command: wget -O /tmp/remote_syslog.tar.gz https://github.com/papertrail/remote_syslog2/releases/download/v0.13/remote_syslog_linux_amd64.tar.gz  creates=/usr/bin/remote_syslog
  - command: tar xzf /tmp/remote_syslog.tar.gz chdir=/tmp/ creates=/usr/bin/remote_syslog
  - command: mv /tmp/remote_syslog/remote_syslog /usr/bin/remote_syslog creates=/usr/bin/remote_syslog
  - file: path=/usr/bin/remote_syslog owner=root group=root mode=0755
  - command: wget -O /etc/init.d/remote_syslog https://raw.githubusercontent.com/papertrail/remote_syslog2/v0.13/examples/remote_syslog.init.d creates=/etc/init.d/remote_syslog
  - file: path=/etc/init.d/remote_syslog owner=root group=root mode=0755
  - file: path=/tmp/remote_syslog/ state=absent
  - file: path=/tmp/remote_syslog.tar.gz state=absent
  - service: name=remote_syslog state=restarted enabled=yes
  - template: src=log_files.yml dest=/etc/log_files.yml owner=root group=root mode=0644